README for doc authors
======================

To start writing a new document, follow these steps:

1) read the README.adoc for the preliminary requirements.

2) create a directory with the same name of the doc title lowercase
with underscore for space.

3) copy a master document from other docs to simplify coherency and
change whatever needs to be changed.

4) follow the convention to call the name of the document with the same
name of the doc project dir

5) if the document is rather large and you want to break it into separate
chapters, follow the convention of calling the chapter files as:

 docname_chapter_name-or-number.adoc

The first _ character will separate the docname from the chapter names
and will guarantee automatic inclusion of the chapters into the final
output formats.

6) when you reach a worthwhile point on your document, create a patch with:

 git add docname
 git commit -m "Added manual docname, first draft"
 git format-patch HEAD^

and send it to the devels or fork with gitbub web interface and ask for
pull merging.

Please, before committing any file, check for functionality, to avoid
breaking automatic compilation of docs.

Happy writing!

