== Building kicad-doc with CMake

Obviously, CMake is required. V2.8 or later is required. Building (once you've got the required pre-requisites) is as simple as:

    cd kicad-doc
    mkdir build
    cd build
    cmake ../
    make

This will translate and build PDF and HTML versions of the documentation.

== PO4A

https://po4a.alioth.debian.org/[PO4A] is required. It's used to perform the
translated documentation.

== ASCIIDOC

http://sourceforge.net/projects/asciidoc/[Asciidoc] is also required for
building the documentation.

Asciidoc is the format of the documentation and is used to generate both PDF
and HTML versions of the documentation.

=== dblatex

http://dblatex.sourceforge.net/[dblatex] is currently required for PDF
documenatation. Usually it's installed as a dependency for Asciidoc on Linux
systems. On Windows, PDF generation is currently broken for Asciidoc because
dblatex is not included.

=== FOP

WARNING: FOP is not currently supported!

It's possible to use https://xmlgraphics.apache.org/fop/[Apache FOP] for PDF
generation with Asciidoc instead of dbaltex and could be added so that PDF
documentation can be generated on Windows, but that is work for the future.
Some people will prefer the output of Apache FOP compared to dblatex. It
brings with it a dependency on a Java runtime.

=== ASCIIDOCTOR

WARNING: ASCIIDOCTOR is not currently supported!

It's possible to use http://asciidoctor.org/[asciidoctor] to produce both HTML
and PDF output (PDF through the
http://asciidoctor.org/docs/convert-asciidoc-to-pdf/[asciidoctor-pdf]
project). Asciidoctor has good development and support, but the PDF generation
is currently missing support for inline images, so it's not currently used. It
brings with it a dependency on Ruby.
