KiCad documentation translation
===============================

To start translating these documents in a new language, follow these steps:

1) read the README.adoc for the preliminary requirements

2) create your language addendum. Do a:

 cp src/YOUR-CHOSEN-MANUAL/po/addendum.template src/YOUR-CHOSEN-MANUAL/po/addendum.NN

where NN is the i18n language code and YOUR-CHOSEN-MANUAL is the name of
the manual dir. For example, for "Getting Started in KiCad" in German do:

 cp src/getting_started_in_kicad/po/addendum.template src/getting_started_in_kicad/po/addendum.de

Edit, translate and add your name to the nationalized addendum for your
credit as a translator.

3) then, for creating your language template, you _should_ do this:

 touch src/YOUR-CHOSEN-MANUAL/po/NN.po
 mkdir build
 cd build
 cmake ..
 make YOUR-CHOSEN-MANUAL_updatepo_NN

where, again, YOUR-CHOSEN-MANUAL is the name of the manual dir, for
example "getting_started_in_kicad" and NN is your i18n language code.

If last command should not work for any reason, it is still possible
to use the old scripts procedure:

 rm -rf build/*
 cd src/YOUR-CHOSEN-MANUAL
 make -f ../../utils/old-build-scripts/Makefile po/NN.po
 cd ../../build
 cmake ..

Edit the resulting ../src/YOUR-CHOSEN-MANUAL/po/NN.po file, starting from
the headers, using a specialized po editor of your choice like poedit,
gtranslator, virtaal, lokalize, emacs, vi, or others.
For example do:

 poedit ../src/getting_started_in_kicad/po/de.po

4) try your translation with a:

 make YOUR-CHOSEN-MANUAL_html_NN

For example:

 make cvpcb_html_it

And see the results with a browser:

 firefox src/cvpcb/it/cvpcb.html

NOTE: you can try other formats like pdf or epub as well. HTML is just
the fastest to build.

NOTE: before commit any result it is recommended to try the other
formats like pdf and epub. These formats sometimes trigger errors that
the other build processes may not see. These errors should never reach
the repository since they may block the site automatic compilation of
the different formats.

5) when you reach 100% of the translation, or simply when you think you
   have done enough work, test your work trying to compile it in the
   various formats. When there are no errors, create a patch with:

 cd ..
 git add src/YOUR-CHOSEN-MANUAL/po/addendum.NN src/YOUR-CHOSEN-MANUAL/po/NN.po
 git commit -m "Added translation for LANGUAGE"
 git format-patch HEAD^

and submit a pull-request on Github.

[NOTE]
====
To do the equivalent of a "make clean" just delete recursively the
content of the build dir with:

 rm -rf build/*

====

Happy translation!
