
== Introduction to Pcbnew

=== Description

Pcbnew is a powerful printed circuit board software tool available
for the Linux, Microsoft Windows and Apple OS X operating systems.
Pcbnew is used in association with the schematic capture 
program Eeschema to create printed circuit boards. 

Pcbnew manages libraries of footprints. Each footprint is a drawing of the
physical component including its land pattern (the layout of pads
on the circuit board). The required footprints are
automatically loaded during the reading of the Netlist. Any changes to footprint
selection or annotation can be changed in the schematic and updated in pcbnew
by regenerating the netlist and reading it in pcbnew again.

Pcbnew provides a design rules check tool which prevents track and pad clearence
issues as well as preventing nets from being connected that aren't connected
in the netlist/schematic. When using the interactive router it continuously 
runs the design rules check and will help automatically route individual traces.

Pcbnew provides a rats nest display, a hairline connecting the pads
of footprints which are connected on the schematic. These connections
move dynamically as track and footprint movements are made.

Pcbnew has a simple but effective autorouter to assist in the
production of the circuit board. An Export/Import in SPECCTRA dsn format
allows the use of more advanced auto-routers.

Pcbnew provides options specifically provided for the production of ultra
high frequency microwave circuits (such as pads of trapezoidal and complex
form, automatic layout of coils on the printed circuit, etc).

=== Principal design features

The smallest unit in pcbnew is 1 nanometer. All dimensions are stored as integer
nanometers.

Pcbnew can generate up to 32 layers of copper, 14 technical layers (silk screen,
solder mask, component adhesive, solder paste and edge cuts) plus
4 auxiliary layers (drawings and comments) and manages in real time
the hairline indication (rats nest) of missing tracks.

The display of the PCB elements (tracks, pads, text, drawings...)
can be customizable:

* In full or outline.
* With or without track clearance.

For the complex circuits the display of layers, zones, components
can be hidden in a selective way for clarity on screen. Nets of traces can be
highlighted to provide high contrast as well.

Footprints can be rotated to any angle, with a resolution of 0.1 degree.

Pcbnew includes a footprint editor that allows editing of individual footprints
that have been on a pcb or editing a footprint in a library.

The footprint editor provides many time saving tools such as:

* Fast pad numbering by simply dragging the mouse over pads in the order you 
  want them numbered.
* Easy generation of rectangular and circular arrays of pads for LGA/BGA 
  or circular footprints.
* Semi-automatic aligning of rows or columns of pads.

Footprint pads have a variety of properties that can be adjusted. The pads can be 
round, rectangular, oval or trapezoidal. For through hole parts drills can be offset
inside the pad and be round or a slot. Individual pads can also be rotated and have
unique soldermask, net, or paste clearence. Pads can also have a solid connection
or a thermal relief connection for easier manufacturing. Any combination of unique
pads can be placed within a footprint.


Pcbnew generates in an extremely simple way all the documents
necessary:

* Fabrication outputs:

** Files for Photoplotters in GERBER RS274X format.

** Files for drilling in EXCELLON format.

* Plot files in HPGL, SVG and DXF format.

* Plot and drilling maps in POSTSCRIPT format.

* Local Printout.

=== General remarks

Due to the degree of control necessary it is highly suggested to use a 3 button 
mouse with pcbnew. Many features such as panning and zooming require a 3 button
mouse.

In the new release of KiCad pcbnew has seen wide sweeping changes from developers
at CERN. This includes features such as a new renderer (OpenGL and Cairo view modes),
an interative push and shove router, differential and meander trace routing and tuning,
a reworked footprint editor, and many other features. Please note that most of
these new features *only* exist in the new OpenGL and Cairo view modes.

Please read through this fully to see what changes have been introduced. If you
want to see what else CERN has on its roadmap for KiCad please check the following
page: http://www.ohwr.org/projects/cern-kicad/wiki/WorkPackages
