== KiCad Scripting Reference

Scripting allow you to automate tasks within KiCad using the https://www.python.org/[Python] language.

Also see the doxygen documentation on http://ci.kicad-pcb.org/job/kicad-doxygen/ws/build/pcbnew/doxygen-python/html/index.html[Python Scripting Reference].

You can see python module help by typing `pydoc pcbnew` on your terminal.

Using scripting you can create:

- *Plugins*: this type of script is loaded when KiCad starts. Examples:
    * *Footprint Wizards*: To help you build footprints easily filling in parameters. See the dedicated section <<Footprint_Wizards,Footprint Wizards>> below.
    * *File I/O* '(planned)': To let you write plugins to export/import other filetypes
    * *Actions* '(planned)': Associate events to scripting actions or register new menus or toolbar icons.

- *Command Line Scripts*: scripts that can be used from the command line, load boards or libraries, modify them, and render outputs or new boards.

It shall be noted that the only KiCad applicaiton that supports
scripting is Pcbnew. It is also planned for Eeschema in the future.

=== KiCad Objects

The scripting API reflects the internal object structure inside KiCad/pcbnew. BOARD is the main object, that has a set of properties and a set of MODULEs, and TRACKs/SEGVIAs, TEXTE_PCB, DIMENSION, DRAWSEGMENT.
Then MODULEs have D_PADs, EDGEs, etc.

- See the BOARD section below.

=== Basic API Reference

All the pcbnew API is provided from the "pcbnew" module in Python. GetBoard() method will return the current pcb open at editor, useful for commands written from the integrated scripting shell inside pcbnew or action plugins.

=== Loading and Saving a Board

- *LoadBoard(filename):*
           loads a board from file returning a BOARD object, using the file format that matches the filename extension.

- *SaveBoard(filename,board):*
           saves a BOARD object to file, using the file format that matches the filename extension.

- *board.Save(filename):*
           same as above, but it's a method of BOARD object.
 
.Example that loads a board, hides all values, shows all references
[source,python]
----------
#!/usr/bin/python
import sys
from pcbnew import *

filename=sys.argv[1]

pcb = LoadBoard(filename)
for module in pcb.GetModules():  
    print "* Module: %s"%module.GetReference()
    module.GetValueObj().SetVisible(False)      # set Value as Hidden
    module.GetReferenceObj().SetVisible(True)   # set Reference as Visible

pcb.Save("mod_"+filename)
----------

=== Listing and Loading Libraries

.Enumerate library, enumerate modules, enumerate pads
[source,python]
----------
#!/usr/bin/python
 
from pcbnew import *
 
libpath = "/usr/share/kicad/modules/sockets.mod"
lst = FootprintEnumerate(libpath)
 
for name in lst:
    m = FootprintLoad(libpath,name)
    print name,"->",m.GetLibRef(), m.GetReference()
    for p in m.GetPads():
        print "\t",p.GetPadName(),p.GetPosition(),p.GetPos0(), p.GetOffset()
----------

=== BOARD

Board is the basic object in KiCad pcbnew, it's the document.

BOARD contains a set of object lists that can be accessed using the following methods, they will return iterable lists that can be iterated using "for obj in list:"

- *board.GetModules():* This method returns a list of MODULE objects, all the modules available in the board will be exposed here.
- *board.GetDrawings():* Returns the list of BOARD_ITEMS that belong to the board drawings
- *board.GetTracks():* This method returns a list of TRACKs an SEGVIAs inside a BOARD
- *board.GetSegZones():* Returns a list of SEGZONEs
- *board.GetFullRatnest():* Returns the list of ratsnets (connections still not routed)
- *board.GetLocalRatsnest():* Returns the list of ratsnest of a moving footprint (as it's dragged)
- *board.GetNetClasses():* Returns the list of net classes
- *board.GetCurrentNetClassName():* Returns the current net class
- *board.GetViasDimensionsList():* Returns the list of Via dimensions available to the board.
- *board.GetTrackWidthList():* Returns the list of Track Widths available to the board.


.Board Inspection Example
[source,python]
----------
#!/usr/bin/python
import sys
from pcbnew import *
 
filename=sys.argv[1]
pcb = LoadBoard(filename)
 
ToUnits=ToMils
FromUnits=FromMils
 
print "LISTING VIAS:"
for item in pcb.GetTracks():
    if type(item) is SEGVIA:

        pos = item.GetPosition()
        drill = item.GetDrillValue()
        width = item.GetWidth()
        print " * Via:   %s - %f/%f "%(ToUnits(pos),ToUnits(drill),ToUnits(width))

    elif type(item) is TRACK:

        start = item.GetStart()
        end = item.GetEnd()
        width = item.GetWidth()

        print " * Track: %s to %s, width %f" % (ToUnits(start),ToUnits(end),ToUnits(width))

    else:
        print "Unknown type    %s" % type(item)

print ""
print "LISTING DRAWINGS:"
for item in pcb.GetDrawings():
    if type(item) is TEXTE_PCB:
        print "* Text:    '%s' at %s"%(item.GetText(),item.GetPosition())
    elif type(item) is DRAWSEGMENT:
        print "* Drawing: %s"%item.GetShapeStr() # dir(item)
    else:
        print type(item)

print ""
print "LIST MODULES:"
for module in pcb.GetModules():
    print "* Module: %s at %s"%(module.GetReference(),ToUnits(module.GetPosition()))

print ""
print "LIST ZONES:"
for zone in pcb.GetSegZones():
    print zone

print ""
print "RATSNEST:",len(pcb.GetFullRatsnest())
---------

=== Examples

==== Change a component pins paste mask margin

.We only want to change pins from 1 to 14, 15 is a thermal pad that must be keep as it is.
[source,python]
----------
b = pcbnew.GetBoard()
u304 = b.FindModuleByReference('U304')
pads = u304.GetPads()
 
for p in pads:
    print p.GetPadName(), pcbnew.ToMM(p.GetLocalSolderPasteMargin())
    id = int(p.GetPadName())
    if id<15: p.SetLocalSolderPasteMargin(0)
---------

[[Footprint_Wizards]]
=== Footprint Wizards

The footprint wizards are a collection of python scripts that can be
access via from the Footprint Editor. If you invoke the footprint
dialog you select a given wizard that allows you to see the footprint
rendered, and you have some parameters you can edit.

If the plugins are not properly distributed to your system package,
you can find the latest versions in the KiCad source tree at
link:http://bazaar.launchpad.net/~kicad-product-committers/kicad/product/files/head:/pcbnew/scripting/plugins/[launchpad].

They should be located in for example `C:\Program
Files\KiCad\bin\scripting\plugins`.

On linux you can also keep your user plugins in
`$HOME/.kicad_plugins`.


.Build footprints easily filling in parameters.
[source,python]
----------
#!/usr/bin/python

from pcbnew import *

class FPCFootprintWizard(FootprintWizardPlugin):
    def __init__(self):
        FootprintWizardPlugin.__init__(self)
        self.name = "FPC"
        self.description = "FPC Footprint Wizard"
        self.parameters = {
             "Pads":
                {"*n":40,           # not internal units preceded by "*"
                 "pitch":           FromMM(0.5),
                 "width":           FromMM(0.25),
                 "height":          FromMM(1.6)},
             "Shield":
                {"shield_to_pad":   FromMM(1.6),
                 "from_top":        FromMM(1.3),
                 "width":           FromMM(1.5),
                 "height":          FromMM(2)}
        }

        self.ClearErrors()

    # build a rectangular pad
    def smdRectPad(self,module,size,pos,name):
            pad = D_PAD(module)
            pad.SetSize(size)
            pad.SetShape(PAD_RECT)
            pad.SetAttribute(PAD_SMD)
            pad.SetLayerMask(PAD_SMD_DEFAULT_LAYERS)
            pad.SetPos0(pos)
            pad.SetPosition(pos)
            pad.SetPadName(name)
            return pad
 
    # This method checks the parameters provided to wizard and set errors
    def CheckParameters(self):
        p = self.parameters      
        pads            = p["Pads"]["*n"]      
        errors = ""
        if (pads<1):
            self.parameter_errors["Pads"]["n"]="Must be positive"
            errors +="Pads/n has wrong value, "
        p["Pads"]["n"] = int(pads)  # make sure it stays as int (default is float)      

        pad_width       = p["Pads"]["width"]
        pad_height      = p["Pads"]["height"]
        pad_pitch       = p["Pads"]["pitch"]
        shl_width       = p["Shield"]["width"]
        shl_height      = p["Shield"]["height"]
        shl_to_pad      = p["Shield"]["shield_to_pad"]
        shl_from_top    = p["Shield"]["from_top"]

        return errors

    # build the footprint from parameters
    def BuildFootprint(self):

        print "parameters:",self.parameters
        #self.ClearErrors()
        #print "errors:",self.parameter_errors

        module = MODULE(None) # create a new module
        self.module = module

        p = self.parameters
        pads            = int(p["Pads"]["*n"])      
        pad_width       = p["Pads"]["width"]
        pad_height      = p["Pads"]["height"]
        pad_pitch       = p["Pads"]["pitch"]
        shl_width       = p["Shield"]["width"]
        shl_height      = p["Shield"]["height"]
        shl_to_pad      = p["Shield"]["shield_to_pad"]
        shl_from_top    = p["Shield"]["from_top"]

        size_pad = wxSize(pad_width,pad_height)
        size_shld = wxSize(shl_width,shl_height)

        module.SetReference("FPC"+str(pads))   # give it a reference name
        module.m_Reference.SetPos0(wxPointMM(-1,-2))
        module.m_Reference.SetPosition(wxPointMM(-1,-2))

        # create a pad array and add it to the module
        for n in range (0,pads):
            pad = self.smdRectPad(module,size_pad,wxPoint(pad_pitch*n,0),str(n+1))
            module.Add(pad)

        pad_s0 = self.smdRectPad(module,
                            size_shld,
                            wxPoint(-shl_to_pad,shl_from_top),
                            "0")
        pad_s1 = self.smdRectPad(module,
                            size_shld,
                            wxPoint((pads-1)*pad_pitch+shl_to_pad,shl_from_top),
                            "0")      

        module.Add(pad_s0)
        module.Add(pad_s1)

        e = EDGE_MODULE(module)
        e.SetStartEnd(wxPointMM(-1,0),wxPointMM(0,0))
        e.SetWidth(FromMM(0.2))
        e.SetLayer(EDGE_LAYER)
        e.SetShape(S_SEGMENT)
        module.Add(e)

        module.SetLibRef("FPC"+str(pads))

# create our footprint wizard
fpc_wizard = FPCFootprintWizard()

# register it into pcbnew
fpc_wizard.register()
---------

