STATUS page for translations
============================

This page contains a reference for translators to organize and avoid
overlap in the translation process of KiCad docs.

If you want to add yourself in the translation effort, please fork, add
your name in this document and ask for a pull. You can do it directly
from the github web interface.

First of all, please read this dir
https://github.com/KiCad/kicad-doc/blob/master/README.adoc[README] and
https://github.com/KiCad/kicad-doc/blob/master/translation_instructions.adoc[translation_instructions]

For an overview of the system and the reasons behind the choice of
asciidoc as a standard for the documentation see the general docs
https://github.com/KiCad/kicad-doc/blob/master/doc/README.adoc[README].

.KiCad Asciidoc Translation Status
[format="csv",cols="3,1^,6",options="header"]
|====
include::i18n_status.csv[]
|====

.I18N Translators
[options="header"]
|====
|Dutch          |French         |German|Italian  |Japanese          |Polish  |Chinese
|M. van den Berg|Pierre Beneteau|      |M. Ciampa|Starfort          |K. Karyu|taotieren      
|               |Martin d'Allens|      |         |Kinichiro Inoguchi|        |Liu HanCheng      
|               |               |      |         |Yoneken           |        |      
|====


Happy translation!
