README for doc authors
======================

To start writing a new document, follow these steps:

1) read the README.adoc for the preliminary requirements.

2) create a directory with the very same name of the doc
title (use the same upper/lover case combination) with
underscore for space. This was choosen to semplify the
Makefile.

3) copy a master document from other docs to semplify
coherency and change whatever needs to be changed.

4) follow the convention to call the name of the 
document with the same name of the doc project dir

5) if the document is rather large and you want to break it into separate
chapters, follow the convention of calling the chapter files as:

 docname_chapter_name-or-number.adoc

The first _ character will separate the docname from the chapter names
and will guarantee automatic inclusion of the chapters into the final
output formats.

6) when you reach a worth point on your document, create a patch with:

 git add docname
 git commit -m "Added manual docname, first draft"
 git format-patch HEAD^

and send it to the devels.

Please, before committing any file, check for functionality, to avoid
breaking automatic compilation of docs.

[NOTE]
==================
For best results for pdf embedded images:

* Use the inline image: command for icons and set icon file image dpi to
  144 using GIMP or imagemagick command:

   for i in * ; do convert -density 144x144 $i x$i ; rm $i ; mv x$i $i ; done

* Use the image:: macro for screenshots using the format parameter 
  scaledwidth="NN%" tuning the NN value for best results.
==================

Happy writing!

