KiCad Documentation
===================

The KiCad software tool come with an additional component library package
and a documentation package. Once you install all three packages you are
set with a full fledged software tool for PCB design. Any necessary
documentation will be then available from the Help menu of each KiCad
application (Eeschema, Cvpcb, etc.).  The same documentation is available
here too.

In this section you can find the official KiCad documentation in various
formats directly pooled from the
https://github.com/ciampix/kicad-doc/tree/master/src/asciidoc[KiCad
experimental documentation repository].

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/KiCad/KiCad.adoc[KiCad Reference Manual]

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/Eeschema/Eeschema.adoc[Eeschema Reference Manual]

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/CvPcb/CvPcb.adoc[Cvpcb Reference Manual]

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/Pcbnew/Pcbnew.adoc[Pcbnew Reference Manual]

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/Gerbview/Gerbview.adoc[Gerbeview Reference Manual]

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/Getting_Started_in_KiCad/Getting_Started_in_KiCad.adoc[Getting
Started in KiCad]: essential and concise guide to mastering kicad for the
successful development of sophisticated electronic printed circuit
boards. 

*Additional documentation*

* https://github.com/ciampix/kicad-doc/blob/master/src/asciidoc/IDF_Exporter/IDF_Exporter.adoc[IDF
Exporter manual]: this is not finished documentation, but is a good
reference to understand how the new IDF export functionality works.

*Developer documentation*

Currently there is three doxygen doc targets available to the developers,
these can be generated with make dev-docs, make doxygen-docs, and make
doxygen-python in the kicad source. For convience they are also available
on the following links and updaged by the Jenkins build server for each
commit, so the ones here should always be the latest. Note that the
doxygen-docs integrate the devdocs also, hence only two are linked here.

* http://ci.kicad-pcb.org/job/kicad-doxygen/ws/Documentation/doxygen/html/index.html[Developers
source code reference and road map]

* http://ci.kicad-pcb.org/job/kicad-doxygen/ws/build/pcbnew/doxygen-python/html/index.html[Python
scripting reference]

*Documentation in other languages*

The KiCad documentation is available in other languages too. Mind that
for languages either than English documents might be outdated.

*Additional tutorials*

A pretty good generic tutorial on how to use KiCad is made by
http://teholabs.com/knowledge/kicad.html[Teho Labs].

*Scripting manuals*

In case you are interesting in scripting, please refer to the
http://www.kicad-pcb.org/display/KICAD/KiCad+Scripting+Reference+Manual[KiCad
Scripting Reference Manual]. 

*KiCad users mailing list*

KiCad users can take advantage of the
https://groups.yahoo.com/neo/groups/kicad-users/info[KiCad users mailing
list] for asking and answering questions. Before jumping in it please try
to find the answers to your questions in the many reference manuals
available.

*KiCad tutorials*

A fun way to start your journey into PCB design with KiCad is to have a
look at the many http://www.kicad-pcb.org/display/KICAD/Tutorials[KiCad
tutorial section].

*Reporting problems*

If you think you want to contribute to the KiCad documentation or if you
want to report a problem, please refer to the
// This does not work...
// http://bazaar.launchpad.net/~kicad-developers/kicad/doc/files/head:/doc/help/en/docs_src/[LibreOffice documentation files] 
// and to the 
https://launchpad.net/~kicad-developers[KiCad developers mailing list].
