
== Introduction to Eeschema

=== Description

Eeschema is a schematic capture software distributed as a part of
KiCad and available under the following operating systems:

* Linux
* Apple macOS
* Windows

Regardless of the OS, all Eeschema files are 100% compatible from one OS
to another.

Eeschema is an integrated application where all functions of drawing,
control, layout, library management and access to the PCB design
software are carried out within Eeschema itself.

Eeschema is intended to cooperate with PcbNew, which is KiCad's printed
circuit design software. It can also export netlist files, which lists
all the electrical connections, for other packages.

Eeschema includes a symbol library editor, which can create and edit
symbols and manage libraries.
It also integrates the following additional but essential functions
needed for modern schematic capture software:

* Electrical rules check (ERC) for the automatic control of incorrect and missing
  connections
* Export of plot files in many formats (Postscript, PDF, HPGL, and SVG)
* Bill of Materials generation (via Python or XSLT scripts, which allow many flexible formats).

=== Technical overview

Eeschema is limited only by the available memory. There is thus no real
limitation to the number of components, component pins, connections or sheets.
In the case of multi-sheet diagrams, the representation is
hierarchical.

Eeschema can use multi-sheet diagrams in a few ways:

* Simple hierarchies (each schematic is used only once).
* Complex hierarchies (some schematics are used more than once with multiple
  instances).
* Flat hierarchies (schematics are not explicitly connected in a master
  diagram).
