
== Introduction to Eeschema

=== Description

Eeschema is powerful schematic capture software distributed as part of
KiCad and available under the following operating systems:

* Linux
* Apple OS X
* Windows

Regardless of the OS, all Eeschema files are 100% compatible from one OS
to another.

Eeschema is an integrated application where all functions of drawing,
control, layout, library management and access to the PCB design
software are carried out within Eeschema itself.

Eeschema is intended to work with PcbNew, which is KiCad's printed
circuit design software. It can also export netlist files, which list
all the electrical connections, for other packages.

Eeschema includes a component symbol editor, which can create and edit
components and manage libraries.
It also integrates the following additional but essential functions
needed for modern schematic capture software:

* Electrical rules check (ERC) for the automatic control of incorrect and missing
  connections
* Export of plot files in many formats (Postscript, PDF, HPGL, and SVG)
* Bill of Materials generation (via Python scripts, which allow many configurable formats).

=== Technical overview

Eeschema is limited only by the available memory. There is thus no real
limitation to the number of components, component pins, connections, or sheets.
In the case of multi-sheet diagrams, the representation is
hierarchical.

Eeschema can use multi-sheet diagrams of these types:

* Simple hierarchies (each schematic is used only once).
* Complex hierarchies (some schematics are used more than once with multiple
  instances).
* Flat hierarchies (schematics are not explicitly connected in a master
  diagram).
